reviews:
  review_status: true            
  request_changes: true          
  post_review_summary: true      
  comment_style: inline          
  enable_tests_check: true       
  enable_security_check: true    
  enable_performance_check: true 

tone:
  style: professional            

chat:
  enable: true                   

knowledge_base:
  enable: true              
